version: "3.9"

services:
  db:
    image: postgres:13.7-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_vol:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: web
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db_pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin_vol:/var/lib/pgadmin
    depends_on:
      - db

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
    depends_on:
      - web

volumes:
  postgres_vol:
  pgadmin_vol:
